matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - make
      script:	make
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew update && brew upgrade && brew install gcc5 && CC=gcc-5 && CXX=g++-5"
      script:	make

before_install:
    - eval "${MATRIX_EVAL}"